// <auto-generated />
using System;
using App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301153131_AddEmailPasswordAuth")]
    partial class AddEmailPasswordAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("App.Models.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kategorie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kilometerstand")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StravaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rads");
                });

            modelBuilder.Entity("App.Models.TeilVorlage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschreibung")
                        .HasColumnType("TEXT");

                    b.Property<string>("FahrradKategorien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Geschwindigkeiten")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gruppe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hersteller")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kategorie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teilvorlagen");
                });

            modelBuilder.Entity("App.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Anzeigename")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("StravaId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TokenExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vorname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Benutzer");
                });

            modelBuilder.Entity("App.Models.WearPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AusbauDatum")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AusbauKilometerstand")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EinbauDatum")
                        .HasColumnType("TEXT");

                    b.Property<int>("EinbauKilometerstand")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kategorie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RadId");

                    b.ToTable("Verschleissteile");
                });

            modelBuilder.Entity("App.Models.WearPart", b =>
                {
                    b.HasOne("App.Models.Bike", null)
                        .WithMany()
                        .HasForeignKey("RadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
