// <auto-generated />
using System;
using App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304072610_AddFahrstundenAndServiceEintrag")]
    partial class AddFahrstundenAndServiceEintrag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Models.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Fahrstunden")
                        .HasColumnType("double precision");

                    b.Property<int>("Kategorie")
                        .HasColumnType("integer");

                    b.Property<int>("Kilometerstand")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StravaId")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Rads");
                });

            modelBuilder.Entity("App.Models.ServiceEintrag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BeiFahrstunden")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notizen")
                        .HasColumnType("text");

                    b.Property<int>("ServiceTyp")
                        .HasColumnType("integer");

                    b.Property<int>("WearPartId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WearPartId");

                    b.ToTable("ServiceEintraege");
                });

            modelBuilder.Entity("App.Models.TeilVorlage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .HasColumnType("text");

                    b.Property<string>("FahrradKategorien")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Geschwindigkeiten")
                        .HasColumnType("integer");

                    b.Property<string>("Gruppe")
                        .HasColumnType("text");

                    b.Property<string>("Hersteller")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Kategorie")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teilvorlagen");
                });

            modelBuilder.Entity("App.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<string>("Anzeigename")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<string>("StravaId")
                        .HasColumnType("text");

                    b.Property<long?>("TokenExpiresAt")
                        .HasColumnType("bigint");

                    b.Property<string>("Vorname")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Benutzer");
                });

            modelBuilder.Entity("App.Models.WearPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AusbauDatum")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("AusbauFahrstunden")
                        .HasColumnType("double precision");

                    b.Property<int?>("AusbauKilometerstand")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EinbauDatum")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("EinbauFahrstunden")
                        .HasColumnType("double precision");

                    b.Property<int>("EinbauKilometerstand")
                        .HasColumnType("integer");

                    b.Property<int>("Kategorie")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notizen")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<int>("RadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RadId");

                    b.ToTable("Verschleissteile");
                });

            modelBuilder.Entity("App.Models.Bike", b =>
                {
                    b.HasOne("App.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Models.ServiceEintrag", b =>
                {
                    b.HasOne("App.Models.WearPart", null)
                        .WithMany()
                        .HasForeignKey("WearPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("App.Models.WearPart", b =>
                {
                    b.HasOne("App.Models.Bike", null)
                        .WithMany()
                        .HasForeignKey("RadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
